# Generated by Django 5.1.6 on 2025-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_campaign_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Field'), ('radio', 'Radio Button'), ('checklist', 'Checklist'), ('rating', 'Rating Scale')], max_length=20),
        ),
    ]
