# Generated by Django 5.1.6 on 2025-03-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
