# Generated by Django 5.1.6 on 2025-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_form_expiration_date_conditionallogic_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Field'), ('radio', 'Radio Button'), ('checklist', 'Checklist'), ('rating', 'Rating Scale'), ('dropdown', 'Dropdown'), ('file_upload', 'File Upload'), ('date_picker', 'Date Picker')], max_length=20),
        ),
    ]
