# Generated by Django 5.1.6 on 2025-03-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_response_is_draft_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='selected_options',
        ),
    ]
