# Generated by Django 5.1.6 on 2025-03-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_response_selected_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='form',
        ),
    ]
