# Generated by Django 5.1.6 on 2025-03-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_campaign_created_by_remove_campaign_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
