# Generated by Django 5.1.7 on 2025-03-19 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_panelist_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='rank',
            field=models.CharField(default='Beginner', max_length=50),
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='core.panelist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
