# Generated by Django 5.1.7 on 2025-03-21 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_badge_panelistbadge_panelist_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ANNOUNCER', 'Announcer'), ('PANELIST', 'Panelist'), ('ADMIN', 'Admin')], max_length=20),
        ),
        migrations.CreateModel(
            name='PanelistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelistResponses', to='core.panelist')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelistResponses', to='core.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
