# Generated by Django 5.1.7 on 2025-04-03 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_announcer_email_alter_panelist_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='expired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=10),
        ),
    ]
